### DISCUSSION TITLE
Welcome to weishaupt_modbus Discussions!

### DISCUSSION THREAD

**Discussion by OStrama** [OStrama/weishaupt_modbus#2] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by edlestau** [comment]
Hi OStrama.
Thanks for sharing this integration!
I will try it next time.

**Comment by maddinhome** [comment]
Hi OStrama,

thank you for sharing this integration!

I try it and it works fine for me. 

keep going.....

**Reply by OStrama** [reply]
Thanks! What type of heatpump do you use?

**Reply by maddinhome** [reply]
It is a WSB 8-A-RME-AI that was installed in February 2024.

**Reply by maddinhome** [reply]
Just for information, in order for the query via Modbus to work, the heat pump must be restarted.

Modbus can be activated in the WEMPortal, but no IP addresses can be entered.
The IP address can only be entered via the control panel of the heat pump in the expert menu.
Of course, Modbus can also be activated in this menu in the control panel.

Edit:

You should perhaps point out that the IP of Homeassistant should be entered for it to work...I don't think that's really clear to everyone. Homeassistant serves as a client and therefore has to be entered in the IP mask.

**Reply by maddinhome** [reply]
Hello, I have created a small visualization for the heating curve and the dashboard:

`type: history-graph
entities:
  - entity: sensor.aussentemperatur
  - entity: sensor.vorlaufsolltemperatur
hours_to_show: 48
title: Heizkurve
logarithmic_scale: true
`

If you have the "mini-graph-card" integration you can also use this: 

`type: custom:mini-graph-card
entities:
  - entity: sensor.vorlaufsolltemperatur
    name: Vorlaufsolltemperatur
  - entity: sensor.vorlauftemperatur
    name: Tatsächliche Vorlauftemperatur
  - entity: sensor.aussentemperatur
    name: Außentemperatur
name: Heizkurve Wärmepumpe
hours_to_show: 24
line_width: 2
show:
  fill: false`

If you change the heating curve, the visualization adapts. But it takes a few minutes. Perhaps you could speed it up so that the effect is immediately visible.

Unfortunately, I don't have an external device and sensors, e.g. in the living room from the heat pump, like you obviously have. Then you could also display the target indoor temperature.

I had to remove your living room sensors from the sample dashboard.

Have a nice day and greetings

**Reply by MadOne** [reply]
An update of the entity should not take minutes. If you change it in HA it should be insant.
This may be the update time of the chart?!?

**Comment by thetschulian** [comment]
Hello, thank you for this great integration.
I own a WBB20 since 10 days.

Some of my values / entities do not reflect the real "values" if I check the control panel for example 
Betriebsstunden E1 = 76 hour  but this "Betriebsstunden" are "Schaltspiele" on the control panel.


I am very new to modbus and even home assistant so I'll maybe ask some dumb questions.

**Reply by OStrama** [reply]
Done in next Version ;-) I assume that the 2nd. Schaltspiele refers to E2? (It is zero in my heatpump, so I cannot confirm..)

**Reply by thetschulian** [reply]
yeah this should be E2.

**Comment by OStrama** [comment]
Thanks for the info! I‘ll update the name in the next release.

Since all the modbus addresses, names and values are collected from different sources, any hints for modifying and adding them are very welcome! This helps all of us to make this more complete..

**Comment by thetschulian** [comment]
Well, since I dont know how to compare the modbus addresses yet, I will provide some screenshots of my WBB20 control panel and my homeassistant values. hopefully this helps.

**Reply by OStrama** [reply]
Could you please test the 0.0.8pre5? It contains HK2..

**Comment by chriscom2020** [comment]
Hi OStrama, thanks for your work. I have the following question: Is Volumenstrom not readable? It shows always the same number (never changing). See attached screenshot.
Thanks for Input!
<img width="377" alt="Screenshot 2024-10-31 103338" src="https://github.com/user-attachments/assets/7abae058-57ed-4de2-93e9-ff7dd77c23d8">

**Reply by john92648** [reply]
Another Question to the Volumenstrom. In the WEP Portal Integration Ist_Volumenstrom was availible, is it possible to get it also in this Integration? and maybe the RPM of the Kompressor?
Regards John

**Reply by MadOne** [reply]
Currently not, as this is not available through modbus. But we are working on integration of the local Webinterface. This provides these values.

**Reply by john92648** [reply]
Thanks for quick answer. BTW I have the Pump configered to Volumenstrom, but the Entität Volumenstrom Heizen kann not be adjusted. Actuel I have 1400l/h.
![Bildschirmfoto 2024-11-27 um 19 13 02](https://github.com/user-attachments/assets/64199a8b-348d-41ea-aab2-2fe2717dcd72)
and the Entität shows me 2.360 l/h
![Bildschirmfoto 2024-11-27 um 19 14 25](https://github.com/user-attachments/assets/b2efdf89-a4b5-4f6d-abc2-54d85f9d4e5a)

**Comment by OStrama** [comment]
It‘s an input value when you use pump control method „Volumenstrom“
I also would need the current value but afaik it‘s not available.
BTW: Some of these entries in principle are writable, but I decided to make them read only to prevent undefined situations..

**Reply by MadOne** [reply]
Should we rename them to "Sollwert Volumenstrom Heizen) for clarification?

**Reply by chriscom2020** [reply]
Thanks for the information. A rename to "Sollwert Volumenstrom" is a good idea!

**Comment by OStrama** [comment]
Yes, makes sense!

**Comment by faulesocke85** [comment]
Thanks for creating this integration! 

Question: Is it possible to get "Vorlauf- und Rücklauftemperatur" of HK1 and HK2? Or is it implemented with e.g. address 31106 which results to value "1?" in my setup? 

I am Running an WBB LB 20 AR. 

Thanks a lot

**Reply by MadOne** [reply]
Hi,

we have "Heizkreis Vorlauftemperatur" (31 105). But at least i have no sensor installed for that. It should not show up if you dont have this sensor installed.
The documentation we have shows now register for "Heizkreis Rücklauftemperatur" but we found the undocumented register you metioned. 31106. This one is always 0 for me. 

Are you sure you have a sensor for heizkreis vorlauf and rücklauf? Can you see this values anywhere? WEM Portal, at device, web interface?

**Comment by OStrama** [comment]
If the register only shows values like 0, 1 or so, it‘s perhaps a status or a configuration but no measurement value..
I also do not have this value afaik (not at home currently, so I cannot check)

**Comment by chriscom2020** [comment]
Hi @OStrama, I have already experimented with the connection and reading of data from the WEM local web server and found that the web server is very slightly overloaded and then no longer reacts or does not release any more data. Did you also have this experience and how do you deal with it? I would be happy about a short exchange...

**Reply by MadOne** [reply]
Hi @chriscom2020 , i also had this problem. 
Our plan is to not stress the server. I got reliable responses with 20 seconds after each request. will will propably increase the time.
When i did a lot of testing the server was not responding anymore. The only solution i found was to restart the heatpump controller.

I hope that the server can manage very little requests and the problem does not "stack". But i am still not sure about that.

**Reply by chriscom2020** [reply]
Hi @MadOne, I experienced about 60 seconds between individual requests, but after approximately 24 hours, the server often stopped responding. While it worked, everything ran smoothly. Restarting the heating controller is, of course, a possible solution, but likely just an emergency fix. Overall, the communication works well with Modbus, but I need the volume flow data (Volumenstrom) for my heating system, which is only accessible via the API or locally. 

Keep up the great work, and thank you for your efforts!

**Reply by OStrama** [reply]
Same here. Also when using via browser, the response time can be very long and from time to time I also see a 404. I think the web server itself has more an experimental state. But I also like to see the flow rate in HA..

**Reply by MadOne** [reply]
My hope was that the reasons i crashed it were too many requests or too many sessions(killing ha).

How did you request the values?

**Reply by edlestau** [reply]
Hello everyone.

Just as a note, in case this is not known: erickastel has created an integration “Weishaupt WEM Portal” and currently has big problems to retrieve data from Weishaupt via API and/or web, because Weishaupt blocks the access partially.
Perhaps you should contact him to coordinate with him on this matter?

**Reply by MadOne** [reply]
> Hello everyone.
> 
> Just as a note, in case this is not known: erickastel has created an integration “Weishaupt WEM Portal” and currently has big problems to retrieve data from Weishaupt via API and/or web, because Weishaupt blocks the access partially.
> Perhaps you should contact him to coordinate with him on this matter?

We are talking about the local Webinterface not the wem portal / api the integration you mentioned is using.

**Reply by chriscom2020** [reply]
Here is my volumenstrom.py as reference...
[volumenstrom_request.py.txt](https://github.com/user-attachments/files/18062293/volumenstrom_request.py.txt)

**Reply by MadOne** [reply]
You are doing a login every time you run the script (every minute). This is what i suspected to stress the server.

We are creating a session and save the cookie. So we stay loggedin and only have to login once or when the cookie expires.

**Reply by chriscom2020** [reply]
I think the way you're doing it is definitely better.

**Reply by MadOne** [reply]
I hope it is enough to not kill the server

**Comment by john92648** [comment]
Hi all, do you try
![Bildschirmfoto 2024-12-09 um 17 27 09](https://github.com/user-attachments/assets/e65227ac-59c6-4e34-94da-32cc384edca6)
 to get this value (Volumenstrom) ?

**Reply by MadOne** [reply]
@john92648 yes.

**Comment by chriscom2020** [comment]
Is there a way to read/get the warning messages from the heat pump? I'm experiencing issues with icing on the blower (Biblock outdoor unit). The heat pump generates two warnings before an error occurs, which then locks the unit. Receiving a notification at the first warning would be incredibly helpful. Any suggestions? Thanks in advance!

**Comment by OStrama** [comment]
Warnings and error messages should be available on the according entities:
![image](https://github.com/user-attachments/assets/89d24a7a-9e94-4e16-a447-1e98192c64d4)
You could create an automation that reacts, i.e., if warning changes from "no error" to something else..

**Reply by chriscom2020** [reply]
Yes, of course! I totally overlooked that and only ever looked at the error messages! My mistake! I added a few warning messages to hpconst.py and now the SMS push to the cell phone works! Thank you!

**Reply by OStrama** [reply]
Ah great! Could you please provide the updated hpconst.py?

**Reply by chriscom2020** [reply]
Yes and another question: Shouldn't these values (65535) be different for SYS_FEHLER and SYS_WARNUNG?

SYS_FEHLER = [
    StatusItem(**65535**,"kein Fehler"),
]

SYS_WARNUNG = [
    StatusItem(**65535**,"keine Warnung"),
    StatusItem(32,"Fehler Kältesatz (32)"),
    StatusItem(43,"Ventilator blockiert (43)"),
    StatusItem(40,"Volumenstrom zu gering (40)"),
    StatusItem(44,"Drehzahl Ventilator zu niedrig (44)"),
    
 I have only added the warnings that I have encountered so far. I'll add the remaining entries when I get the time for it...

**Reply by chriscom2020** [reply]
[hpconst.py.txt](https://github.com/user-attachments/files/18390072/hpconst.py.txt)

**Comment by OStrama** [comment]
Thanks! Will update the repository and add them to the next release.

**Reply by chriscom2020** [reply]
Are you planning to develop the webif topic further? I can hardly wait to no longer be dependent on the weishaupt server... I'm particularly interested in the volume flow, of course, since it doesn't work via modbus... Keep up the good work, 1.06 works perfectly here!

**Reply by MadOne** [reply]
Yes we do. But its hard to develop. While develpement the webif often freezes. I hope this does not happen in produciton.
Wenn the webif freezes the controller does some crazy things. The device has to be powered off completely.
I don't want to do that when the heatpump is running.
So this will be a lot easier when its not as cold anymore.

**Reply by chriscom2020** [reply]
Thanks for the feedback! Yes, I also noticed the freezing, the webserver is not particularly stable. For a reset, it may be sufficient to deactivate the webserver in the professional menu and reactivate it again, of course only if you have physical access to the device...

**Reply by MadOne** [reply]
Sadly this is not sufficient.
When the webserver freezes the heatpump controller also struggles.

**Reply by chriscom2020** [reply]
...that probably means that I have not yet managed to freeze the webserver completely, good to know! The heat pump controller, on the other hand, has crashed several times and only disconnecting it from the power supply has helped...

**Comment by MarcoK87** [comment]
Hey there! Great work, congrats! I am really happy with this integration :-)

One question: is it possible to activate/deavtivate vacation mode via modbus?

**Reply by MadOne** [reply]
No it isnt.

**Comment by OStrama** [comment]
Basically, you could do the same by an automation that switches to lowering mode at defined dates..

**Comment by MNG314** [comment]
Hello all,

I aktivated the Modbus on my WBB12 yesterday and set up your integration. So far it works well, thanks for your effort!

I have some issues and wishes:
1. Values of "Schaltspiele" and "Betriebsstunden": E1 and E2 are swapped
3. I tried to integrate the energy consumption statistics in the energy tab of HomeAssistant. Since there are only integer values read from the WBB, the step increase by 1kWh leads to a wrong display in the 1h binned histogram stats of the detailed device consumption with negative values. Is there another way to integrate? The heat pump at least provides kWh values with one digit precision for daily statistics in the machine display. It would be ideal to have an all time consumption counter with >1 digit precision.
4. For optimisation of the efficiency (COP) it would be great to have the actual values of WBB consumption power / delivered power (W) / COP and other values that are only shown in the OEM info display of the machine. Would it be possible to integrate these parameters/entities? This would also solve point 2. ;-)

Michael

**Comment by MadOne** [comment]
1. This is a bug on the heatpump side. See https://github.com/OStrama/weishaupt_modbus/blob/d30705a1212413e38367745881376f96089a4d50/custom_components/weishaupt_modbus/hpconst.py#L1323 + following
2. It is not. We only get integers over modbus.
3. We read all values available on modbus. 

There is a webinterface that provides more and more acurate values. I hope i can work on integrating that into our integration soon. But this will take some time.

**Comment by freto036** [comment]
I have just gotten started with Ha, as I hope to mainly use it as an energy management system once our solar system goes life. For that reason I have added your integration as well and though I hardly understand half of the stuff it has added so far, I was wondering whether the circulation pump for the warm water circuit can be switched via modbus. 
I have an automation running via HA, based on a Google calendar, which turns on the coffee maker 30 minutes before my alarm goes off, which changes on a daily basis.
The circulation pump is currently on a timer, which covers most, but not all of my shifts. I would love if I could set the pump to "always on" but then cut the power via modbus and add it to said automation. So if somebody can tell me if (and how) that works, I would be very happy. There's not many things that stuck more at 4am than wasting cold water, waiting for it to turn warm in order to take a shower...

Edit: It's a WBB 12 A RMD AI by the way.

**Reply by MadOne** [reply]
Hi,

sadly the circulation pump is NOT controllable via modbus. But easily achive the desired behavour with buying a ha compatible smartplug/reiais.

**Reply by Ideefiks** [reply]
Hi,

The circulation pump ALONE is not controllable via modbus but you can launch a warmwater push, which would also activate the circulation pump. It would of course also trigger warmwater production but that is likely wanted anyway. I coupled it with a light switch that supports a long push, removing the need for a dedicated smart plug or relais. I also coupled it with some lights that briefly flash for visual confirmation the warmwater push was launched

**Comment by rediculum** [comment]
Awesome! Thanks for the integration. I already started adding each single address from the Weishaupt Modbus XLS table when I found your integration. I have a WWP LS 16 and used the Kennfeld for the LS 8 and 90% works fine. The rest of the 10% are "unknown" values but not that important to me. Maybe also because my WP is currently running in summer mode and not using any watt of energy :)

**Comment by ksh12** [comment]
Hello,
I just came to know through the Facebook group about this integration.
Is LS8 fully supported?

I wasn't aware how integrations work and I built my dashboard from scratch by reading all modbus sensors (I learnt home assistant in past few days :)  )
Currently for me the E1 registers are not working for LS8 at 34106 address.
Are you also using 34106 for LS8 E1 switchings or do you use different modbus addresses for LS8?
Thanks!

**Comment by Ideefiks** [comment]
Hi all, thought i’d share how I use this great integration, curious to see what everybody came up with! 

I have two circuits, floor heating and radiators, the first one is the only one controlled by a room thermostat and dissipates the majority of the heat generated by the heatpump. That creates some control issues, such as:
- I cannot have room correction on the radiators as Weishaupt does not allow coupling the room thermostat with both circuits
- Initially temperatures rise slowly as the entire floor is slowly heating, once the mixing valve starts to close temperatures suddenly rise quickly, leading to overshoots and oscillating power requests
- Those problems combine when target temperatures for both circuits become too close, creating coupling effects between the controllers of the mixing valve and power request

With automations I can:
- control the spread between the target temperatures of both circuits (essentially keeping the radiators always at 5 or 5.5° warmer than the floor), removing coupling effects and the need for a second thermostat
- control heating and cooling not only through the summer temperature setting of Weishaupt but a combination of various temperatures, including non-Weishaupt
- use summer mode dynamically to further increase efficiency
- enhance Weishaupt weather control by not only reacting to outside temperature changes but anticipate based on the weather forecast (e.g. if tomorrow is going to be sunny I reduce the room target temperature in anticipation)
- briefly increase the floor heating after an oil recirculation or warmwater cycle as these can cause totally unnecessary start / stops of the heatpump
- temporarily reduce the radiator temperature after a standstill to avoid a quick restart
- reduce the radiator temperature after the mixing valve closes to reduce the power request and avoid overshoots
- Anticipate warmwater cycles and launch one if the heatpump is about to enter a standstill in moderate seasons, avoiding a start / stop

This results in stable working of the heatpump, with a minimum starts and comfortable temperatures year-long

**Reply by OStrama** [reply]
Great!
You solved a lot of issues that are also bothering me and perhaps also other users. 
Although I only have one radiator circuit it would be very interesting to see how you solved the oil return issue and the control by weather forecast.

Another issue that I have is that the heat pump tries to reach the defined temperature too fast. This leads to a too high power request and as a consequence a steep rise of the flow temperature. Especially with outside temperatures around 5 degree it happens quite often that the heatpump now stops before the temperatures and the power request have a chance to be settled..

What do you think? Would it be possible to share your automations s as yaml files here in the repository?

**Reply by Ideefiks** [reply]
Sure, happy to share 😄

My automations are often specific to my set-up and many became much more complicated because I needed to tackle unwanted interactions between them (for example, while I temporarily lower the radiator target temperature because I want to avoid a quick restart, another automation that controls the spread between target temperatures should not increase it again!). As many of these automations temporarily change things I use timers and other helpers to store the settings before my changes.

Anyway, let’s start with the oil recirculation as that is a relatively easy one to explain and I found it frustratingly stupid to see the heat pump stop just because the target temp was very briefly exceeded, knowing it was going to drop quickly after the 6mins oil recirculation cycle. I also assume this can be adapted to all setups (because I have two circuits I manipulate only the floor for this one, which is circuit3, dumping the excess heat quickly without impacting the higher target temp of the heat pump). 

My actual YAML for this one is 500+ lines for various reasons so I will post a simplified version here, you also need to create a timer and select helper to store the operationmode of the circuit you are going to manipulate. 

UPDATE: I could simplify these automations a lot by choosing any of the operation modes and only using that one, changing only the associated target room temperature. Downside is that I would have to recreate a lot stuff that currently works AND I would loose some visibility in my dashboard on what my automations are up to, for example it might show that floor is on lowering because tomorrow will be sunny. That is easier to understand than room target temperature for the floor is on 20° instead of 20.5° because tomorrow will be sunny. Manipulating the room target temperatures for different circuits is also why I created issue 123 😅

````

alias: Oil recirculation simplified
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.wh_warmepumpe_betrieb
    to: heatpump_operationmode_oilrecirculation
    id: Oil return
  - trigger: state
    entity_id:
      - timer.timer_circuit3_increased
    to: idle
    id: Timer_circuit3_increased_ended
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.wh_warmepumpe_betrieb
        state: heatpump_operation_cooling
  - condition: state
    entity_id: select.wh_warmwasser_warmwasser_push
    state: ww_push_aus
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Oil return
          - condition: numeric_state
            entity_id: sensor.wh_heizkreis3_vorlaufsolltemperatur3
            above: 1
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: select.wh_heizkreis3_betriebsart3
                    state:
                      - hz_operationmode_normal
                sequence:
                  - action: input_select.select_option
                    metadata: {}
                    data:
                      option: Normal
                    target:
                      entity_id: input_select.remember_operation_mode_circuit_3
                  - action: select.select_option
                    metadata: {}
                    target:
                      entity_id: select.wh_heizkreis3_betriebsart3
                    data:
                      option: hz_operationmode_comfort
                  - action: timer.start
                    metadata: {}
                    data:
                      duration: "00:06"
                    target:
                      entity_id: timer.timer_circuit3_increased
                alias: operation mode is normal
              - conditions:
                  - condition: state
                    entity_id: select.wh_heizkreis3_betriebsart3
                    state:
                      - hz_operationmode_lowering
                sequence:
                  - action: input_select.select_option
                    metadata: {}
                    data:
                      option: Lowering
                    target:
                      entity_id: input_select.remember_operation_mode_circuit_3
                  - action: select.select_option
                    metadata: {}
                    target:
                      entity_id: select.wh_heizkreis3_betriebsart3
                    data:
                      option: hz_operationmode_comfort
                  - action: timer.start
                    metadata: {}
                    data:
                      duration: "00:10"
                    target:
                      entity_id: timer.timer_circuit3_increased
                alias: Operation mode is lowering
      - conditions:
          - condition: trigger
            id:
              - Timer_circuit3_increased_ended
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.remember_operation_mode_circuit_3
                    state: Lowering
                  - condition: not
                    conditions:
                      - condition: state
                        entity_id: select.wh_heizkreis3_betriebsart3
                        state:
                          - hz_operationmode_lowering
                sequence:
                  - action: select.select_option
                    metadata: {}
                    target:
                      entity_id: select.wh_heizkreis3_betriebsart3
                    data:
                      option: hz_operationmode_lowering
              - conditions:
                  - condition: state
                    entity_id: input_select.remember_operation_mode_circuit_3
                    state: Normal
                  - condition: not
                    conditions:
                      - condition: state
                        entity_id: select.wh_heizkreis3_betriebsart3
                        state:
                          - hz_operationmode_normal
                sequence:
                  - action: select.select_option
                    metadata: {}
                    target:
                      entity_id: select.wh_heizkreis3_betriebsart3
                    data:
                      option: hz_operationmode_normal
              - conditions:
                  - condition: state
                    entity_id: input_select.remember_operation_mode_circuit_3
                    state: Comfort
                  - condition: not
                    conditions:
                      - condition: state
                        entity_id: select.wh_heizkreis3_betriebsart3
                        state:
                          - hz_operationmode_comfort
                sequence:
                  - action: select.select_option
                    metadata: {}
                    target:
                      entity_id: select.wh_heizkreis3_betriebsart3
                    data:
                      option: hz_operationmode_comfort
mode: single

````
