### DISCUSSION TITLE
Dimplex si8tu

### DISCUSSION THREAD

**Discussion by grericht** [OStrama/weishaupt_modbus#55] [Q&A]
I have a dimplex si8tu
this has the pco5+ module installed. It also has a LAN card installed and an RTMEcon is connected to J23 FBus2.
I have integrated the heat pump into Home Assistant using various http requests. The control system in particular is very complicated.
Now I have come across this option. Can I also use it for my heat pump? I need a ModBus module on an ESP32 with ESPHome? I don't have a clue how to start it.
I would like to leave out the RTMEcon. But I need it because the passive cooling seems to need a temperature and humidity sensor.

**Comment by MadOne** [comment]
Hi,

i have no clue about the devices you are talking about. I know some weishaupt heatpumps are rebranded dimplex.
Can you enable modbus in the settings. We are using modbusTCP (over ethernet), so if you are lucky you already have everything you need.

**Comment by grericht** [comment]
![Screenshot 2024-11-29 210218](https://github.com/user-attachments/assets/5889e532-0c2f-4dbb-b7c7-7e24a06f3ba6)
this means ther is modbusTCP?
![IMG_20241121_091714](https://github.com/user-attachments/assets/00064c77-da90-4d12-bb63-7546aaf11782)
here is my pco5+

**Reply by MadOne** [reply]
To me this looks like modbus tcp is enabled on port 502 (default)

**Comment by grericht** [comment]
then i have to ask a stupid question: how can i conect to the heatpump over modbustcp?
the pco5+ is linked to my private network. i can reach over the configured ip adress.
![Screenshot 2024-11-29 210822](https://github.com/user-attachments/assets/fc7685fd-33c1-4d02-808c-76c0978d995e)
looks like this. but is hard for me to get the values in my home assistant and harder to control them.

**Reply by MadOne** [reply]
You need a modbus client. Homeassistant has a modbus integration (client) configurable through yaml

**Reply by MadOne** [reply]
Perhaps you just try our integration and hope you get reasonable values?

**Reply by grericht** [reply]
try but ther are no entities
![Screenshot 2024-11-29 212728](https://github.com/user-attachments/assets/01c0fade-dade-4823-8736-09eceda6570b)

**Reply by grericht** [reply]
this is my heatpump wiki:
https://dimplex.atlassian.net/wiki/spaces/DW/pages/3303571457/Modbus+TCP+Anbindung
but i dont know what is the correct yaml code:
modbus:
  - name: "dimplex"
    type: tcp
    host: 192.168.188.94
    port: 502
    sensors:
      - name: "Dimplex Mode"
        slave: 1
        address: 5007
        scan_interval: 5
        input_type: input
      - name: "Dimplex Smart Grid"
        slave: 1
        address: 5167
        scan_interval: 5
        input_type: input
      - name: "Dimplex Parallel Displacement"
        slave: 1
        address: 5002
        scan_interval: 5
        input_type: input

**Reply by grericht** [reply]
i works. yeah. thankx

modbus:
  - name: "dimplex"
    type: tcp
    host: 192.168.188.94
    port: 502
    sensors:
      - name: "Wärmemenge Heizen 1-4"
        slave: 1
        address: 5096
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Heizen 5-8"
        slave: 1
        address: 5097
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Heizen 9-12"
        slave: 1
        address: 5098
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Warmwasser 1-4"
        slave: 1
        address: 5099
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Warmwasser 5-8"
        slave: 1
        address: 5100
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Warmwasser 9-12"
        slave: 1
        address: 5101
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Schwimmbad 1-4"
        slave: 1
        address: 5102
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Schwimmbad 5-8"
        slave: 1
        address: 5103
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "Wärmemenge Schwimmbad 9-12"
        slave: 1
        address: 5104
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

**Reply by grericht** [reply]
reading is fine. but actually i couldnt write a value.

i try this may:
```
automation:
  - alias: "Aktualisiere Wärmepumpe"
    trigger:
      - platform: state
        entity_id: input_button.trigger_heatpump_update
    action:
      - service: modbus.write_register
        data:
          hub: dimplex
          unit_id: 1
          address: 5066  # Beispieladresse für Start Stunde 1
          value:
            - "{{ states('input_number.start_stunde_1') | int }}"
      - service: modbus.write_register
        data:
          hub: dimplex
          unit_id: 1
          address: 5067  # Beispieladresse für Start Minute 1
          value:
            - "{{ states('input_number.start_minute_1') | int }}"
```

**Reply by adobe-hills** [reply]
Hi @grericht,
looks like you have also a Dimplex pco5 steering heat pump. I have a similar machine and want to start bringing it to home assistant. Do you now have more register in your yaml file. Maybe you are so kind to share this modbus yaml? I never used modbus before, perhaps it will be easier for me to start with, if I have a starting yaml file.
Thx so much

**Comment by grericht** [comment]
sorry for my late answer. here is my working code:

```
input_number:
  start_stunde_1:
    name: "Start Stunde 1"
    min: 0
    max: 23
    step: 1

  start_minute_1:
    name: "Start Minute 1"
    min: 0
    max: 59
    step: 1

  warmwasser_soll:
    name: "Warmwasser Soll"
    min: 30
    max: 85
    step: 1
    
  # Weitere Helfer für andere Werte hinzufügen...

input_button:
  trigger_heatpump_update:
    name: "Wärmepumpe aktualisieren"
    
automation:
  - alias: "Aktualisiere Wärmepumpe"
    trigger:
      - platform: state
        entity_id: input_button.trigger_heatpump_update
    action:
      - service: modbus.write_register
        data:
          hub: dimplex_si8tu
          unit: 1
          address: 5047
          value:
            - "{{ states('input_number.warmwasser_soll') | int }}"

modbus:
  - name: "dimplex_si8tu"
    type: tcp
    host: !secret wp_ip
    port: !secret wp_modbus_port

    binary_sensors:
    
      - name: "dimplex_si8tu Digital"
        address: 1
        slave: 1
        slave_count: 207
        input_type: coil
        scan_interval: 5
        unique_id: dimplex_si8tu_digital
        
    sensors:
    
      - name: "dimplex_si8tu Integer"
        address: 5045
        slave: 1
        count: 3
        input_type: holding
        data_type: custom
        structure: ">3h"
        scan_interval: 5
        unique_id: dimplex_si8tu_integer

      - name: "dimplex_si8tu Warmwasser Hysterese"
        slave: 1
        address: 5045
        input_type: holding
        unit_of_measurement: "K"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Solltemperatur"
        slave: 1
        address: 5047
        input_type: holding
        unit_of_measurement: "°C"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Solltemperatur Minimal"
        slave: 1
        address: 5145
        input_type: holding
        unit_of_measurement: "°C"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Solltemperatur Maximal"
        slave: 1
        address: 5048
        input_type: holding 
        unit_of_measurement: "°C" 
        scan_interval: 10 

      - name: "dimplex_si8tu Warmwasser Sperre"
        slave: 1
        address: 5065
        input_type: holding
        unit_of_measurement: ""
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Start Stunde 1"
        slave: 1
        address: 5066
        input_type: holding
        unit_of_measurement: "hour"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Start Minute 1"
        slave: 1
        address: 5067
        input_type: holding
        unit_of_measurement: "min"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Ende Stunde 1"
        slave: 1
        address: 5068
        input_type: holding
        unit_of_measurement: "hour"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Ende Minute 1"
        slave: 1
        address: 5069
        input_type: holding
        unit_of_measurement: "min"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Start Stunde 2"
        slave: 1
        address: 5070
        input_type: holding
        unit_of_measurement: "hour"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Start Minute 2"
        slave: 1
        address: 5071
        input_type: holding
        unit_of_measurement: "min"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Ende Stunde 2"
        slave: 1
        address: 5072
        input_type: holding
        unit_of_measurement: "hour"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Ende Minute 2"
        slave: 1
        address: 5073
        input_type: holding
        unit_of_measurement: "min"
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Sonntag"
        slave: 1
        address: 5074
        input_type: holding
        unit_of_measurement: ""
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Montag"
        slave: 1
        address: 5075
        input_type: holding
        unit_of_measurement: ""
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Dienstag"
        slave: 1
        address: 5076
        input_type: holding
        unit_of_measurement: ""
        scan_interval: 10

      - name: "dimplex_si8tu Warmwasser Sperre Mittwoch"
        slave: 1
        address: 5077
        input_type: holding 
        unit_of_measurement: "" 
        scan_interval: 10 

      - name: "dimplex_si8tu Warmwasser Sperre Donnerstag" 
        slave: 1 
        address: 5078 
        input_type: holding 
        unit_of_measurement: "" 
        scan_interval: 10 

      - name: "dimplex_si8tu Warmwasser Sperre Freitag" 
        slave: 1 
        address: 5079 
        input_type: holding 
        unit_of_measurement: "" 
        scan_interval: 10 

      - name: "dimplex_si8tu Warmwasser Sperre Samstag" 
        slave: 1 
        address: 5080 
        input_type: holding 
        unit_of_measurement: "" 
        scan_interval: 10 

      - name: "dimplex_si8tu Wärmemenge Heizen 1-4"
        slave: 1
        address: 5096
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Heizen 5-8"
        slave: 1
        address: 5097
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Heizen 9-12"
        slave: 1
        address: 5098
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Warmwasser 1-4"
        slave: 1
        address: 5099
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Warmwasser 5-8"
        slave: 1
        address: 5100
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Warmwasser 9-12"
        slave: 1
        address: 5101
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Schwimmbad 1-4"
        slave: 1
        address: 5102
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Schwimmbad 5-8"
        slave: 1
        address: 5103
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10

      - name: "dimplex_si8tu Wärmemenge Schwimmbad 9-12"
        slave: 1
        address: 5104
        input_type: holding
        unit_of_measurement: "kWh"
        scan_interval: 10
```
