### ISSUE TITLE
Add derived entity for "schaltspiele_verdichter" and JAZ

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#38]
**Is your feature request related to a problem? Please describe.**
I noticed additional entity **`warmepumpe_schaltspiele_verdichter`** in [web portal integration](https://github.com/erikkastelec/hass-WEM-Portal) and used this in my dash board.

<img width="304" alt="image" src="https://github.com/user-attachments/assets/c3f5d4fb-57e1-4adf-864e-c3f00c9336ca">

**Describe the solution you'd like**
This information is useful for operation and configuration. Is it possible to provide **`schaltspiele_verdichter`** also for modbus integration?
<img width="350" alt="image" src="https://github.com/user-attachments/assets/512942b7-4389-4e99-8291-1b1ba694afe6">

**Describe alternatives you've considered**
My current implementation uses this sensor definition.

```
    # Wärmepumpe TAZ
    - name: "WPP TAZ"
      unique_id: "wpp_taz"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.weishaupt_wbb_gesamt_energie_heute')) / float(states('sensor.weishaupt_wbb_elektr_energie_heute')))|round(1) }}
    - name: "WPP MAZ"
      unique_id: "wpp_maz"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.weishaupt_wbb_gesamt_energie_monat')) / float(states('sensor.weishaupt_wbb_elektr_energie_monat')))|round(1) }}
    - name: "WPP JAZ"
      unique_id: "wpp_jaz"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.weishaupt_wbb_gesamt_energie_jahr')) / float(states('sensor.weishaupt_wbb_elektr_energie_jahr')))|round(1) }}
    # Wärmepumpe Verdichter Schaltspiele heute
    - name: "WPP Verdichter Schaltspiele heute"
      unique_id: "wpp_verdichter_schaltspiele_heute"
      state_class: measurement
      icon: mdi:counter
      state: >
        {{float(states('sensor.warmepumpe_schaltspiele_verdichter')) | round(0) - float(states('sensor.wpp_schaltspiele_end_of_day')) | round(0)}}
      availability: "{{ has_value('sensor.warmepumpe_schaltspiele_verdichter') and has_value('sensor.wpp_schaltspiele_end_of_day')}}"
- trigger:
    - trigger: time
      at: "00:01:00"
  sensor:
    - name: "WPP Schaltspiele - End of Day"
      unique_id: "wpp_schaltspiele_end_of_day"
      state_class: total_increasing
      icon: mdi:counter
      state: >
        {{ states('sensor.warmepumpe_schaltspiele_verdichter')| round(0) }}
      availability: "{{ has_value('sensor.warmepumpe_schaltspiele_verdichter') }}"

```

**Comment by OStrama** [comment]
AFAIK „Schaltspiele Verdichter“ is not on the Modbus. But it should be possible to trigger on „Leistungsanforderung“ changes from 0 to >0…

**Comment by Bertk** [comment]
Yes, I suppose so.

**Comment by MadOne** [comment]
The webif provides these values

**Comment by Bertk** [comment]
I tried to implement "WPP Schaltspiele gesamt" using helper for input number and automation "Update Schaltspiele" which increments the number whenever state "Standzeit" occurs. After some hours I got different results for the for 'sensor.warmepumpe_schaltspiele_verdichter' and 'input_number.wpp_schaltspiele_gesamt'.  I am not sure which one is the correct way to count "Schaltspiele". Any idea?

`sensor.weishaupt_wbb_betriebsanzeige` states `[Standzeit|Warmwasserbetrieb|Heizbetrieb|Abtauen]`

<img width="866" alt="image" src="https://github.com/user-attachments/assets/824cc655-e7d3-468d-92b3-d0b5a24c4cdb">

```
alias: Update Schaltspiele
description: Inkrementiere  wpp_schaltspiele_gesamt für Standzeit Leistungsanforderung
triggers:
  - trigger: state
    entity_id:
      - sensor.weishaupt_wbb_betriebsanzeige
    to: Standzeit
    for:
      hours: 0
      minutes: 0
      seconds: 5
    from: null
conditions: []
actions:
  - action: input_number.increment
    metadata: {}
    data: {}
    target:
      entity_id: input_number.wpp_schaltspiele_gesamt
mode: single
```

![image](https://github.com/user-attachments/assets/229183c9-7d11-473a-8dbf-8c779159fb37)

**Comment by Bertk** [comment]
Looks like “Abtauen” add 3  to “Schaltspiele” entity. Is this correct?

<img width="950" alt="image" src="https://github.com/user-attachments/assets/6b9201ce-1aeb-4e9b-aef2-2473c0a718b7">

**Comment by MadOne** [comment]
![image](https://github.com/user-attachments/assets/e67af558-4ac7-403e-bfe7-02fcc69cdd83)

**Comment by MadOne** [comment]
I see no multi step in the whole last week. 
I don't hink we can integrate a sensor like this with calculations as it is tied to statistcs.
I will close this issue/ request. Feel free to create a discussion if you want additional info.

**Comment by MadOne** [comment]
Sounds good. The end results should into the Wiki page?!

**Comment by Bertk** [comment]
Some changes after _**weishaupt_modbus 1.0.4**_ update.

**Automation:**

```yml
alias: Update Schaltspiele
description: Inkrementiere  wpp_schaltspiele_gesamt für Standzeit Leistungsanforderung
triggers:
  - trigger: state
    entity_id:
      - sensor.wh_system_betriebsanzeige
    to: sys_betrieb_19
    for:
      hours: 0
      minutes: 0
      seconds: 5
    from: null
    id: wpp-standzeit
  - trigger: state
    entity_id:
      - sensor.wh_system_betriebsanzeige
    from: null
    to: sys_betrieb_15
    id: wpp-abtauen
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - wpp-standzeit
        sequence:
          - action: input_number.increment
            metadata: {}
            data: {}
            target:
              entity_id: input_number.wpp_schaltspiele_gesamt
      - conditions:
          - condition: trigger
            id:
              - wpp-abtauen
        sequence:
          - action: input_number.set_value
            data_template:
              entity_id: input_number.wpp_schaltspiele_gesamt
              value: >-
                {{ (states.input_number.wpp_schaltspiele_gesamt.state | int ) +
                1 }}
          - action: input_number.increment
            metadata: {}
            data: {}
            target:
              entity_id: input_number.wpp_schaltspiele_abtauen
mode: single
```

**Template:**

```
    # Wärmepumpe JAZ
    - name: "WPP JAZ Tag"
      unique_id: "wpp_jaz_tag"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.wh_statistik_gesamt_energie_heute')) / float(states('sensor.wh_statistik_elektr_energie_heute')))|round(1) }}
    - name: "WPP JAZ Monat"
      unique_id: "wpp_jaz_monat"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.wh_statistik_gesamt_energie_monat')) / float(states('sensor.wh_statistik_elektr_energie_monat')))|round(1) }}
    - name: "WPP JAZ Jahr"
      unique_id: "wpp_jaz_jahr"
      state_class: measurement
      icon: mdi:sigma
      state: >
        {{ (float(states('sensor.wh_statistik_gesamt_energie_jahr')) / float(states('sensor.wh_statistik_elektr_energie_jahr')))|round(1) }}
    # Wärmepumpe Verdichter Schaltspiele heute
    - name: "WPP Verdichter Schaltspiele heute"
      unique_id: "wpp_verdichter_schaltspiele_heute"
      state_class: measurement
      icon: mdi:counter
      state: >
        {{float(states('input_number.wpp_schaltspiele_gesamt')) | round(0) - float(states('sensor.wpp_verdichter_schaltspiele_end_of_day')) | round(0)}}
      availability: "{{ has_value('input_number.wpp_schaltspiele_gesamt') and has_value('sensor.wpp_verdichter_schaltspiele_end_of_day')}}"
- trigger:
    - trigger: time
      at: "00:01:00"
  sensor:
    - name: "WPP Verdichter Schaltspiele - End of Day"
      unique_id: "wpp_verdichter_schaltspiele_end_of_day"
      state_class: total_increasing
      icon: mdi:numeric
      state: >
        {{ states('input_number.wpp_schaltspiele_gesamt')| round(0) }}
    - name: "WPP Abtauen Schaltspiele - End of Day"
      unique_id: "wpp_abtauen_schaltspiele_end_of_day"
      state_class: total_increasing
      icon: mdi:numeric
      state: >
        {{ states('input_number.wpp_schaltspiele_abtauen')| round(0) }}

```
